# Generated by Django 2.2.12 on 2021-07-02 09:50

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/product', verbose_name='Image', width_field='width'),
        ),
    ]
