# Generated by Django 2.2.12 on 2021-07-02 09:54

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_workshop', '0002_auto_20210702_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/product', verbose_name='image'),
        ),
    ]
