# Generated by Django 2.2.12 on 2021-07-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_workshop', '0004_auto_20210704_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='api_workshop.invoice'),
        ),
    ]
