# Generated by Django 2.2.12 on 2021-07-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_workshop', '0006_auto_20210704_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('sended', 'sended'), ('cancle', 'cancle')], default='wait', max_length=40, null=True),
        ),
    ]
