# Generated by Django 2.2.12 on 2021-07-05 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_workshop', '0007_auto_20210704_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='api_workshop.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_workshop.Product'),
        ),
    ]
