# Generated by Django 3.2.5 on 2021-07-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_workshop', '0008_auto_20210705_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
    ]
